### PR TITLE
Allow aeson 1.5

### PR DESCRIPTION
**Pull request by felixonmars**
Tested to build fine.

### CODE REVIEW

**Comment by bubba** [comment]
Ping @hvr, this would be nice to unblock a chain of aeson upgrades needed for https://github.com/haskell/haskell-language-server/pull/161

**Comment by bubba** [comment]
@vijayphoenix is there a second maintainer/hackage trustee for this package?

**Comment by vijayphoenix** [comment]
I don't think so.

**Comment by vijayphoenix** [comment]
@bubba Merging the PR.

However, I will not be able to release this modification on hackage.

**Comment by phadej** [comment]
Doug made a revision: https://hackage.haskell.org/package/HsYAML-aeson-0.2.0.0/revisions/

**Pull request merged**
